version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cohort_checks:
    run: python:latest python analysis/cohort_checks.py
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/cohort_checks.csv

  transform:
    run: python:latest python analysis/transform.py output/input.csv
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/cohort.pickle

  compute_uptake_for_paper:
    run: python:latest python analysis/compute_uptake_for_paper.py
    needs: [transform]
    outputs:
      moderately_sensitive:
        cohort: output/*/cumulative_coverage/*/*/*.csv

  generate_outputs:
    run: python:latest python analysis/generate_all_charts_and_tables.py
    needs: [transform, compute_uptake_for_paper]
    outputs:
      moderately_sensitive:
        charts: output/*/charts/*.png
        reports: output/*/reports/*.html
        tables: output/*/tables/*.csv
